// packages/pro-svelte/src/form/pro-form.svelte
<script lang="ts">
import { validateField } from '@package/pro-core/src/form/schema';

import type { Snippet } from 'svelte';
import type { ProFormGroup, ProFormValues } from '@package/pro-core/src/form/schema';

interface Props {
  schema: Array<ProFormGroup>;
  defaultValues: ProFormValues;
  submitLabel?: string;
  cancelLabel?: string;
  pending?: boolean;
  onSubmit: (values: ProFormValues) => Promise<void> | void;
  onCancel?: () => void;
  children?: Snippet;
}

let {
  schema,
  defaultValues,
  submitLabel = 'Save',
  cancelLabel = 'Cancel',
  pending = false,
  onSubmit,
  onCancel,
}: Props = $props();

let values = $state<ProFormValues>({ ...defaultValues });
let errors = $state<Record<string, string>>({});
let submitting = $state(false);

const submittingNow = $derived(pending || submitting);

async function handleSubmit(event: SubmitEvent) {
  event.preventDefault();
  let valid = true;
  const nextErrors: Record<string, string> = {};
  for (const group of schema) {
    for (const field of group.fields) {
      const error = validateField(field, values[field.name]);
      if (error !== undefined) {
        nextErrors[field.name] = error;
        valid = false;
      }
    }
  }
  errors = nextErrors;
  if (!valid) return;
  submitting = true;
  try {
    await onSubmit({ ...values });
  } finally {
    submitting = false;
  }
}
</script>

<form class="flex flex-col gap-6" onsubmit={handleSubmit}>
  {#each schema as group, gi (gi)}
    <section class="flex flex-col gap-4">
      {#if group.title !== undefined || group.description !== undefined}
        <div class="flex flex-col gap-0.5 pb-1">
          {#if group.title !== undefined}<h3 class="text-sm font-semibold">{group.title}</h3>{/if}
          {#if group.description !== undefined}
            <p class="text-xs text-muted-foreground">{group.description}</p>
          {/if}
        </div>
      {/if}

      <div
        class={group.layout === 'grid-2'
          ? 'grid grid-cols-1 gap-4 sm:grid-cols-2'
          : 'flex flex-col gap-4'}
      >
        {#each group.fields as field (field.name)}
          <div class="flex flex-col gap-2">
            {#if field.type !== 'checkbox' && field.type !== 'switch'}
              <label for={"pro-sv-" + field.name} class="text-sm font-medium">{field.label}</label>
            {/if}

            {#if field.type === 'textarea'}
              <textarea
                id={"pro-sv-" + field.name}
                class="min-h-16 w-full rounded-[10px] border border-input bg-fill px-3 py-2 text-sm outline-none placeholder:text-muted-foreground focus:border-primary/60 focus:bg-card focus:ring-[3px] focus:ring-ring/30"
                placeholder={field.placeholder}
                disabled={field.disabled}
                bind:value={values[field.name] as string}
              />
            {:else if field.type === 'number'}
              <input
                id={"pro-sv-" + field.name}
                type="number"
                class="h-9 w-full rounded-[10px] border border-input bg-fill px-3 text-sm outline-none focus:border-primary/60 focus:bg-card"
                placeholder={field.placeholder}
                disabled={field.disabled}
                bind:value={values[field.name]}
              />
            {:else if field.type === 'select'}
              <select
                id={"pro-sv-" + field.name}
                class="h-9 w-full rounded-[10px] border border-input bg-fill px-2.5 text-sm outline-none focus:border-primary/60 focus:bg-card"
                disabled={field.disabled}
                bind:value={values[field.name] as string}
              >
                {#each field.options ?? [] as option (option.value)}
                  <option value={option.value}>{option.label}</option>
                {/each}
              </select>
            {:else if field.type === 'switch'}
              <label
                class="inline-flex h-[31px] w-[51px] cursor-pointer items-center rounded-full bg-fill p-[2px] transition-colors has-[input:checked]:bg-green"
              >
                <input
                  type="checkbox"
                  class="peer sr-only"
                  role="switch"
                  bind:checked={values[field.name] as boolean}
                />
                <span
                  class="size-[27px] rounded-full bg-white shadow transition-transform peer-checked:translate-x-5"
                />
              </label>
            {:else if field.type === 'checkbox'}
              <label class="inline-flex cursor-pointer items-center gap-2 text-sm">
                <input
                  type="checkbox"
                  class="size-4 rounded accent-[var(--primary)]"
                  bind:checked={values[field.name] as boolean}
                />
                {field.placeholder ?? field.label}
              </label>
            {:else}
              <input
                id={"pro-sv-" + field.name}
                type="text"
                class="h-9 w-full rounded-[10px] border border-input bg-fill px-3 text-sm outline-none placeholder:text-muted-foreground focus:border-primary/60 focus:bg-card focus:ring-[3px] focus:ring-ring/30"
                placeholder={field.placeholder}
                disabled={field.disabled}
                bind:value={values[field.name] as string}
              />
            {/if}

            {#if errors[field.name] !== undefined}
              <p class="text-xs font-medium text-destructive" role="alert">{errors[field.name]}</p>
            {:else if field.description !== undefined && field.type !== 'switch'}
              <p class="text-xs text-muted-foreground">{field.description}</p>
            {/if}
          </div>
        {/each}
      </div>
    </section>
  {/each}

  <div class="flex items-center justify-end gap-2 border-t pt-4">
    {#if onCancel !== undefined}
      <button
        type="button"
        class="h-9 rounded-[10px] border border-border bg-card px-4 text-sm font-medium hover:bg-accent active:scale-[0.98]"
        onclick={onCancel}
      >
        {cancelLabel}
      </button>
    {/if}
    <button
      type="submit"
      disabled={submittingNow}
      class="h-9 rounded-[10px] bg-primary px-4 text-sm font-medium text-primary-foreground shadow-xs transition-all hover:brightness-110 active:scale-[0.98] disabled:opacity-40"
    >
      {submittingNow ? 'Saving…' : submitLabel}
    </button>
  </div>
</form>

// packages/pro/src/form/pro-form.tsx
import { useForm } from '@tanstack/react-form';

import { Button } from '@package/ui/src/components/ui/button';
import { Checkbox } from '@package/ui/src/components/ui/checkbox';
import { Input } from '@package/ui/src/components/ui/input';
import { Label } from '@package/ui/src/components/ui/label';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@package/ui/src/components/ui/select';
import { Switch } from '@package/ui/src/components/ui/switch';
import { Textarea } from '@package/ui/src/components/ui/textarea';
import { cn } from '@package/ui/src/lib/cn';

import type { ReactNode } from 'react';
import type {
  ProFieldSchema,
  ProFormGroup,
  ProFormValues,
} from '@package/pro-core/src/form/schema';

export interface ProFormProps {
  schema: Array<ProFormGroup>;
  defaultValues: ProFormValues;
  submitLabel?: string;
  cancelLabel?: string;
  pending?: boolean;
  onSubmit: (values: ProFormValues) => Promise<void> | void;
  onCancel?: () => void;
  className?: string;
}

function FieldControl({
  schema,
  value,
  error,
  disabled,
  onChange,
}: {
  schema: ProFieldSchema;
  value: unknown;
  error?: string;
  disabled?: boolean;
  onChange: (value: unknown) => void;
}) {
  switch (schema.type) {
    case 'textarea':
      return (
        <Textarea
          value={String(value ?? '')}
          onChange={(event) => onChange(event.target.value)}
          placeholder={schema.placeholder}
          disabled={disabled}
          aria-invalid={error !== undefined}
        />
      );
    case 'number':
      return (
        <Input
          type='number'
          value={value === undefined || value === null ? '' : String(value)}
          onChange={(event) =>
            onChange(event.target.value === '' ? undefined : Number(event.target.value))
          }
          placeholder={schema.placeholder}
          disabled={disabled}
          aria-invalid={error !== undefined}
        />
      );
    case 'select':
      return (
        <Select
          value={typeof value === 'string' ? value : ''}
          onValueChange={(next) => onChange(next)}
          disabled={disabled}
        >
          <SelectTrigger className='w-full' aria-invalid={error !== undefined}>
            <SelectValue placeholder={schema.placeholder ?? 'Select…'} />
          </SelectTrigger>
          <SelectContent>
            {(schema.options ?? []).map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      );
    case 'checkbox':
      return (
        <div className='flex items-center gap-2'>
          <Checkbox checked={!!value} onCheckedChange={(checked) => onChange(!!checked)} />
          <span className='text-sm'>{schema.placeholder ?? schema.label}</span>
        </div>
      );
    case 'switch':
      return (
        <Switch checked={!!value} onCheckedChange={(checked) => onChange(checked)} />
      );
    default:
      return (
        <Input
          value={String(value ?? '')}
          onChange={(event) => onChange(event.target.value)}
          placeholder={schema.placeholder}
          disabled={disabled}
          aria-invalid={error !== undefined}
        />
      );
  }
}

function FieldRow({
  schema,
  children,
}: {
  schema: ProFieldSchema;
  children: ReactNode;
}) {
  const isCheckLike = schema.type === 'checkbox' || schema.type === 'switch';
  return (
    <div className='flex flex-col gap-2'>
      {!isCheckLike && <Label htmlFor={`pro-field-${schema.name}`}>{schema.label}</Label>}
      {children}
      {schema.description !== undefined && !isCheckLike && (
        <p className='text-xs text-muted-foreground'>{schema.description}</p>
      )}
    </div>
  );
}

/** Schema-driven form on TanStack Form; renders every group and field type. */
export function ProForm({
  schema,
  defaultValues,
  submitLabel = 'Save',
  cancelLabel = 'Cancel',
  pending = false,
  onSubmit,
  onCancel,
  className,
}: ProFormProps) {
  const form = useForm({
    defaultValues: defaultValues as ProFormValues,
    onSubmit: async ({ value }) => {
      await onSubmit(value);
    },
  });

  return (
    <form
      className={cn('flex flex-col gap-6', className)}
      onSubmit={(event) => {
        event.preventDefault();
        event.stopPropagation();
        void form.handleSubmit();
      }}
    >
      {schema.map((group, groupIndex) => (
        <section key={groupIndex} className='flex flex-col gap-4'>
          {(group.title !== undefined || group.description !== undefined) && (
            <div className='flex flex-col gap-0.5 pb-1'>
              {group.title !== undefined && (
                <h3 className='text-sm font-semibold'>{group.title}</h3>
              )}
              {group.description !== undefined && (
                <p className='text-xs text-muted-foreground'>{group.description}</p>
              )}
            </div>
          )}
          <div
            className={
              group.layout === 'grid-2' ? 'grid grid-cols-1 gap-4 sm:grid-cols-2' : 'flex flex-col gap-4'
            }
          >
            {group.fields.map((field) => (
              <form.Field
                key={field.name}
                name={field.name as never}
                validators={{
                  onChange: ({ value }) => {
                    for (const validate of field.validators ?? []) {
                      const message = validate(value);
                      if (message !== undefined) return message;
                    }
                    if (field.required && (value === undefined || value === '')) {
                      return `${field.label} is required`;
                    }
                    return undefined;
                  },
                }}
              >
                {(api) => {
                  const errors = api.state.meta.errors;
                  const firstError =
                    typeof errors[0] === 'string' ? errors[0] : String(errors[0] ?? '');
                  return (
                    <FieldRow schema={field}>
                      <FieldControl
                        schema={field}
                        value={api.state.value as unknown}
                        error={firstError || undefined}
                        disabled={field.disabled}
                        onChange={(next) => api.handleChange(next as never)}
                      />
                      {firstError !== '' && (
                        <p className='text-xs font-medium text-destructive' role='alert'>
                          {firstError}
                        </p>
                      )}
                      {field.type === 'switch' || field.type === 'checkbox' ? (
                        <Label
                          htmlFor={`pro-field-${field.name}`}
                          className='mt-1 text-xs text-muted-foreground'
                        >
                          {field.description ?? field.label}
                        </Label>
                      ) : null}
                    </FieldRow>
                  );
                }}
              </form.Field>
            ))}
          </div>
        </section>
      ))}

      <div className='flex items-center justify-end gap-2 border-t pt-4'>
        {onCancel !== undefined && (
          <Button type='button' variant='outline' onClick={onCancel}>
            {cancelLabel}
          </Button>
        )}
        <Button type='submit' disabled={pending}>
          {pending ? 'Saving…' : submitLabel}
        </Button>
      </div>
    </form>
  );
}
