// apps/vue-playground/src/App.vue
<script setup lang="ts">
import { ListTodoIcon, PenSquareIcon } from 'lucide-vue-next';
import { computed, ref } from 'vue';

import FormsView from './views/forms-view.vue';
import TodosView from './views/todos-view.vue';
import AppShell from '@package/pro-vue/src/layout/app-shell.vue';

const views = {
  '/todos': { label: 'Todos', component: TodosView },
  '/forms': { label: 'Form blocks', component: FormsView },
} as const;

type ViewPath = keyof typeof views;

const activePath = ref<ViewPath>('/todos');
const navItems = computed(() => [
  { label: 'Todos', path: '/todos', icon: ListTodoIcon },
  { label: 'Form blocks', path: '/forms', icon: PenSquareIcon },
]);
</script>

<template>
  <AppShell
    title="Universal Blocks — Vue"
    :nav-items="navItems"
    :active-path="activePath"
    @navigate="activePath = $event as ViewPath"
  >
    <component :is="views[activePath].component" />
  </AppShell>
</template>

// apps/svelte-playground/src/App.svelte
<script lang="ts">
import { QueryClient, QueryClientProvider } from '@tanstack/svelte-query';
import { ListTodoIcon, PenSquareIcon } from 'lucide-svelte';

import FormsView from './views/forms-view.svelte';
import TodosView from './views/todos-view.svelte';
import AppShell from '@package/pro-svelte/src/layout/app-shell.svelte';

const queryClient = new QueryClient({
  defaultOptions: { queries: { retry: 1, refetchOnWindowFocus: false } },
});

const navItems = [
  { label: 'Todos', path: '/todos', icon: ListTodoIcon },
  { label: 'Form blocks', path: '/forms', icon: PenSquareIcon },
];

let activePath = $state('/todos');
</script>

<QueryClientProvider client={queryClient}>
  <AppShell title="Universal Blocks — Svelte" {navItems} {activePath} onnavigate={(p) => (activePath = p)}>
    {#snippet headerExtra()}
      <span></span>
    {/snippet}
    {#snippet children()}
      {#if activePath === '/todos'}
        <TodosView />
      {:else}
        <FormsView />
      {/if}
    {/snippet}
  </AppShell>
</QueryClientProvider>
